---
- name: Déploiement de la stack Docker pour Arcdata avec fichiers de configuration
  hosts: all
  become: yes

  vars:
    project_path: /home/ubuntu/docker/arcdata-project/arcdata-site

  tasks:
    - name: Créer le dossier projet si absent
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Copier docker-compose.yml
      copy:
        src: ./arcdata-project/docker-compose.yml
        dest: "{{ project_path }}/docker-compose.yml"
        mode: '0644'

    - name: Copier prometheus.yml
      copy:
        src: ./arcdata-project/prometheus.yml
        dest: "{{ project_path }}/prometheus.yml"
        mode: '0644'

    - name: Ajouter utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Lancer la stack Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ project_path }}"

