---
- name: Installer Docker et Docker Compose
  hosts: all
  become: yes

  tasks:
    - name: Installer les paquets nécessaires pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker officiel
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Installer docker-ce et docker-ce-cli
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Installer docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Ajouter l'utilisateur actuel au groupe docker
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Démarrer et activer le service Docker
      service:
        name: docker
        state: started
        enabled: yes

